name: tigergraph-ml
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - conda
  - pip
  - matplotlib-base
  - numpy
  - scipy
  - pandas
  - pytorch
  - cpuonly
  - pyg
  - tensorboard
  - jupyterlab-git
  - pip:
    - pyTigerGraph
    - tgml[pyg]
    - tigergraph-mlworkbench
    
